### ISSUE TITLE
Animation Complete event

### ISSUE THREAD

**Issue by jdbosley** [specious/cloud9carousel#10]
Not an issue as much as a feature request, but it would be great to have an event fire once an entire animation is completed so additional animations or logic can be started once a user has clicked an item and it's been brought to the front.

**Comment by specious** [comment]
I appreciate the suggestion.  I [added](https://github.com/specious/cloud9carousel/tree/cb3076cbc8037ea5014abdc4195c43aeeee392fb#event-callbacks) `onAnimationFinished()` in 2.0.5.
