### ISSUE TITLE
Provide a 2.0.4 Release or Tag

### ISSUE THREAD

**Issue by jgeorgeson** [specious/cloud9carousel#13]
I notice that the published NPM module is at 2.0.4 but there's no corresponding release or tag here in Github. A little thing I know, but it came up as part of some 3rd party record keeping with my employer.

**Comment by specious** [comment]
2.0.4 [tagged](https://github.com/specious/cloud9carousel/tree/2.0.4).

Thanks for letting me know this can be important.
