### ISSUE TITLE
did't get class to identify which one is active 

### ISSUE THREAD

**Issue by sivu07** [specious/cloud9carousel#17]
worstttt slider I have ever seen 
at least you should add class to that div which is coming in front as active 
div are just rotating right and left

and if i'm adding two slider in single page, double worst

**Comment by specious** [comment]
Thank you for your review of this free open source component.  Perhaps you could make it better and open a pull request, but please consider code quality and the objective as well as subjective value of any trade-offs between useful features and code complexity.

For now, @killexx and I figured out how to label the front item as "active" in #15.

**Comment by specious** [comment]
New option in 2.2.0, `frontItemClass` automatically tags the frontmost item.  See: #15.
