### ISSUE TITLE
Touch support on on mobile

### ISSUE THREAD

**Issue by IShinkarenko** [specious/cloud9carousel#20]
Hello!
Thank u for this cool plugin.
What about touch support on on mobile?

**Comment by specious** [comment]
Touch swipe functionality is not integrated into the carousel plugin itself.

However, the [Julemagne Davidius fine art gallery demo](http://specious.github.io/portfolio/demos/julemagne/) shows how touch support can be [added](https://github.com/specious/portfolio/blob/2baacc42cb5e7ee57b530659bc1bc4032f9b0366/demos/julemagne/js/site.js#L84) easily via @stephband's [jquery.event.move](https://github.com/stephband/jquery.event.move) and [jquery.event.swipe](https://github.com/stephband/jquery.event.swipe) modules.
