### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by hamncheez** [specious/cloud9carousel#22]
Any tips/suggestions on how to do multiple instances? I've tried $("#first, #second").Cloud9Carousel() and it does create multiple, but then all the parameters, previous/next buttons, etc affect all of them

**Comment by specious** [comment]
You're instantiating them with the same options.  Call `Cloud9Carousel()` constructor with different options on each one:

```js
$("#first").Cloud9Carousel( ... )
$("#second").Cloud9Carousel( ... )
```

**Comment by hamncheez** [comment]
Ah! The function calls were being echoed in two different templates, each wrapped in their own window.load(), so only the second one would execute. I used window.addEventListener('load', function(){...}) instead and it works great (had to wait to jquery to load).
