### ISSUE TITLE
Basic Example does not work

### ISSUE THREAD

**Issue by danielimmke** [specious/cloud9carousel#25]
After trial and error, I was only able to get this library to work when I set a specific class name for all the items in the carousel and defined it using the `itemClass` property. It wasn't able to read basic section (parent) -> img (child elements) syntax automatically.

The only other thing I can think of is that I was using `<section>` not `<div>`. Figured I'd post it as an issue.

**Comment by specious** [comment]
By design, carousel items must carry a class name that matches the carousel's `itemClass` field, which can be overridden.

See: [Carousel options](https://github.com/specious/cloud9carousel/tree/059d0b7e859c9449c4ae42a64bb2367182cf0e55#carousel-options)
