### ISSUE TITLE
How to use carousel with WordPress

### ISSUE THREAD

**Issue by nongadroid** [specious/cloud9carousel#26]
Hi, thanks for your work. very good project
But I want to integrate the carousel in a wordpress page but it don't works, I don't know why, maybe the Jquery don't work well with wordpress.
Help me please
Thanks a lot

**Comment by specious** [comment]
What is your approach for integrating the carousel into your WordPress site?

If you're editing the theme files directly, there should be no problem including the jQuery library and creating carousel instances just like in the [examples](https://github.com/specious/cloud9carousel/tree/gh-pages).

Better integration with WordPress could be made possible by creating a [WordPress plugin](https://codex.wordpress.org/Writing_a_Plugin).

**Comment by nongadroid** [comment]
HI, Thanks for your quick answering. I want to edit theme files directly, but it don't work
If I paste the code I get this blank page.
the link of page is: https://www.amirtech-group.com/nos-produits/
Thanks for your Help.
Sincerely!!!
![fail](https://user-images.githubusercontent.com/24754997/33110533-5d63a690-cf40-11e7-8ee2-84026f58bf4a.png)

**Comment by specious** [comment]
I took a quick look at your source code, and I can see why the carousel isn't working.

You've got `<p>` HTML tags [all over](https://user-images.githubusercontent.com/451178/33111354-97caa1d2-cf1b-11e7-9072-c6e250916039.png) your JavaScript code.

I appreciate you reaching out, however this is not an issue with the carousel library or its ability to be integrated into WordPress.

There are good resources on the web for getting help on building custom extensions for WordPress, including [StackExchange](https://wordpress.stackexchange.com/) and the [WordPress forums](https://wordpress.org/support/forum/wp-advanced/).  If you do get it working, and you have any specific wisdom to share, please do comment on this thread.  It would be much appreciated.

**Comment by nongadroid** [comment]
Ok thanks. I will try to do a plugin.
Sincerely
