### ISSUE TITLE
onAnimationFinished one firing once

### ISSUE THREAD

**Issue by krankymonkee** [specious/cloud9carousel#29]
thanks for your work on this - super cool!
Is onAnimationFinished supposed to fire with each rotation, or only after the first?  I am only seeing it fire on the initial load of the carousel.  I am hoping to fire off a function on each finish of rotation.

**Comment by krankymonkee** [comment]
I see what I did here - I had it running as
onAnimationFinished: myfunction()

instead of :
onAnimationFinished: function( carousel ) {
		myfunction();
	}

Thanks again for a great tool!

**Comment by specious** [comment]
Should fire every time the carousel stops spinning.
