### ISSUE TITLE
Scaling carousel on page resize

### ISSUE THREAD

**Issue by BenDeGiglio** [specious/cloud9carousel#30]
Is there a way to re-trigger the function that sizes and scales the images? 
As it is right now, they way I have it set up with percentage based sizing, if you resize the window the carousel looks wonky and only looks right again if you refresh the page.

I attempted to write a resize function that re-instantiates the carousel upon window resize but the issue with that is It resets the carousel to the first image which is undesirable.

**Comment by specious** [comment]
See if the temporary solution posted in #28 works for you.
