### ISSUE TITLE
looping carousel item doesn't work

### ISSUE THREAD

**Issue by rahulkumarshaw** [specious/cloud9carousel#32]
<div  id="carousel" style="height:600px;" *ngFor="let item of items">
   <img class="cloud9-item" src="{{item.imageUrl}}" alt="Item #1" >
</div>
image is displayed but not in carousel view. Carousel seems not to work in case of using *ngFor.

**Comment by specious** [comment]
I gather you are using this module in the context of the Angular framework. I currently have no real experience with Angular, so I'm not sure how to answer your question. If I understand correctly what you are asking, it is how to instantiate the carousel with the Angular framework. In that case, discussion #18 may be relevant.

Please reopen this issue if it's distinctly different.
