### ISSUE TITLE
how to destroy slider?

### ISSUE THREAD

**Issue by voyik** [specious/cloud9carousel#5]
Hi!  How can i destroy slider and then initialize it again ?   

For example on window resize  my images change their sizes  and i want to reinitialize slider with new image sizes ...

**Comment by specious** [comment]
I think you can achieve that by changing the carousel's attributes on the fly.  You can obtain a reference to the carousel object using `$("#carousel").data('carousel')`.  For example,

```js
var carousel = $("#carousel").data('carousel');
carousel.farScale = 0.4;
carousel.render();
```

This changes the scaling of the items as they become more distant, and immediately re-renders the carousel to show the new appearance.

Here's a live demo: http://jsbin.com/hiwopisowe/1/edit?output

**Comment by voyik** [comment]
tnx :+1:
